# Generated by Django 5.2.4 on 2025-08-06 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone_principal', models.CharField(max_length=20, verbose_name='Telefone Principal')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('tipo_cliente', models.CharField(choices=[('COMPRADOR', 'Comprador'), ('VENDEDOR', 'Vendedor'), ('LOCATARIO', 'Locatário'), ('LOCADOR', 'Locador'), ('INVESTIDOR', 'Investidor'), ('OUTRO', 'Outro')], default='COMPRADOR', max_length=10, verbose_name='Tipo de Cliente')),
                ('preferencias_imovel', models.TextField(blank=True, null=True, verbose_name='Preferências do Imóvel')),
                ('orcamento_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Orçamento Máximo')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nome_completo'],
            },
        ),
    ]
